import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'AR' | 'EN' | 'TR';
type Theme = 'light' | 'dark';

export interface User {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  role: 'client' | 'admin';
  phone?: string;
}

interface AppContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  t: (key: string) => string;
  user: User | null;
  setUser: (user: User | null) => void;
}

export const translations = {
  AR: {
    login_title: 'تسجيل الدخول',
    login_subtitle: 'يرجى إدخال بياناتك',
    signup_title: 'إنشاء حساب جديد',
    signup_subtitle: 'انضم إلينا وابدأ مشاريعك',
    full_name: 'الاسم الكامل',
    first_name: 'الاسم الأول',
    last_name: 'اسم العائلة',
    email_address: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirm_password: 'تأكيد كلمة المرور',
    remember_me: 'تذكرني',
    forgot_password: 'هل نسيت كلمة المرور؟',
    sign_in: 'تسجيل الدخول',
    new_client: 'ليس لديك حساب؟',
    create_account: 'إنشاء حساب',
    already_have_account: 'لديك حساب بالفعل؟',
    phone_number: 'رقم الهاتف',
    verify_email: 'يرجى التحقق من بريدك الإلكتروني',
    password_reset_sent: 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
    passwords_do_not_match: 'كلمات المرور غير متطابقة',
    signup_failed: 'فشل إنشاء الحساب',
    user_already_exists: 'المستخدم موجود بالفعل',
    account_created_successfully: 'تم إنشاء الحساب بنجاح',
    login_failed: 'فشل تسجيل الدخول',
    invalid_credentials: 'بيانات الدخول غير صحيحة',
    enter_email_reset: 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.',
    cancel: 'إلغاء',
    send_reset_link: 'إرسال رابط إعادة التعيين',
    tagline: 'حوّل أفكارك إلى واقع مع شركتنا APPTECH SYSTEMS',
    validation_email_required: 'يرجى إدخال البريد الإلكتروني',
    validation_email_invalid: 'صيغة البريد الإلكتروني غير صحيحة (مثال: example@domain.com)',
    validation_password_required: 'يرجى إدخال كلمة المرور',
    validation_first_name_required: 'يرجى إدخال الاسم الأول',
    validation_last_name_required: 'يرجى إدخال الاسم الأخير',
    validation_phone_required: 'يرجى إدخال رقم الجوال',
    validation_password_length: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    faq: 'الأسئلة الشائعة',
    faq_title: 'الأسئلة الشائعة',
    faq_subtitle: 'إجابات على الأسئلة الأكثر شيوعاً',
    faq_q1: 'كيف يمكنني تتبع تقدم مشروعي؟',
    faq_a1: 'يمكنك تتبع تقدم مشروعك من خلال لوحة التحكم الخاصة بك. ستجد تحديثات دورية ومراحل المشروع المكتملة.',
    faq_q2: 'ما هي طرق الدفع المقبولة؟',
    faq_a2: 'نقبل الدفع عبر البطاقات الائتمانية (فيزا، ماستركارد) والتحويل البنكي.',
    faq_q3: 'كيف يمكنني التواصل مع فريق الدعم؟',
    faq_a3: 'يمكنك التواصل معنا عبر البريد الإلكتروني أو من خلال نظام التذاكر في لوحة التحكم.',
    faq_q4: 'هل يمكنني تعديل تفاصيل المشروع بعد البدء؟',
    faq_a4: 'نعم، يمكنك طلب تعديلات، ولكن قد يؤثر ذلك على الجدول الزمني والتكلفة حسب حجم التعديلات.',
    faq_q5: 'أين أجد الفواتير الخاصة بي؟',
    faq_a5: 'جميع الفواتير متاحة في قسم "الفواتير والمدفوعات" ويمكنك تحميلها بصيغة PDF.',
    home: 'الصفحة الرئيسية',
    dashboard: 'لوحة التحكم',
    projects: 'مشاريعي',
    invoices: 'الفواتير والمدفوعات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    logout_confirm: 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    account_settings: 'إعدادات الحساب',
    manage_account_desc: 'تحديث بيانات ملفك الشخصي وإعدادات الأمان الخاصة بك',
    settings_updated: 'تم تحديث إعدادات الحساب بنجاح',
    passwords_dont_match: 'كلمات المرور الجديدة غير متطابقة',
    personal_info: 'المعلومات الشخصية',
    email: 'البريد الإلكتروني',
    phone: 'رقم الجوال',
    security: 'الأمان وكلمة المرور',
    current_password: 'كلمة المرور الحالية',
    new_password: 'كلمة المرور الجديدة',
    confirm_new_password: 'تأكيد كلمة المرور الجديدة',
    save_changes: 'حفظ التغييرات',
    language: 'اللغة',
    theme: 'المظهر',
    user_name: 'أحمد محمد',
    user_role: 'عميل',
    light_mode: 'فاتح',
    dark_mode: 'داكن',
    order_completion: 'إتمام الطلب',
    back_home: 'العودة إلى الصفحة الرئيسية',
    project_details: 'بيانات المشروع',
    confirm_order: 'تأكيد الطلب',
    payment: 'الدفع',
    project_name: 'اسم المشروع',
    project_desc: 'وصف المشروع',
    design_notes: 'ملاحظات التصميم (اختياري)',
    upload_files: 'رفع ملفات التصميم (اختياري)',
    drag_drop: 'اسحب وأفلت الملفات هنا أو اضغط للاختيار',
    upload_hint: 'يمكنك رفع صور، ملفات PDF، أو ملفات مضغوطة',
    add_more_files: 'إضافة المزيد من الملفات',
    next_step: 'الخطوة التالية',
    order_summary: 'ملخص الطلب',
    selected_package: 'الباقة المختارة',
    execution_time: 'مدة التنفيذ',
    total_cost: 'التكلفة الإجمالية',
    working_days: 'أيام عمل',
    currency: '$',
    contract_title: 'الشروط والأحكام وعقد تقديم الخدمات البرمجية',
    contract_doc_title: 'عقد تقديم خدمات تقنية',
    contract_doc_no: 'وثيقة رقم:',
    contract_intro: 'تم إبرام هذا العقد بين كل من:',
    contract_party1: 'الطرف الأول (مقدم الخدمة):',
    contract_party1_name: 'APPTECH SYSTEMS',
    contract_party2: 'الطرف الثاني (العميل):',
    contract_party2_name: 'صاحب مشروع',
    contract_clause1_title: 'البند الأول: موضوع العقد',
    contract_clause1_desc: 'يلتزم الطرف الأول بتطوير وتنفيذ المشروع البرمجي المتفق عليه وفقاً للمواصفات والمتطلبات التي قدمها الطرف الثاني، والتي تعتبر جزءاً لا يتجزأ من هذا العقد.',
    contract_clause2_title: 'البند الثاني: نطاق العمل',
    contract_clause2_desc: 'يشمل نطاق العمل تصميم وتطوير واجهات المستخدم، برمجة قواعد البيانات، وربط واجهات برمجة التطبيقات (APIs) اللازمة لعمل النظام بشكل متكامل كما هو موضح في وثيقة المتطلبات.',
    contract_clause3_title: 'البند الثالث: التزامات الطرفين',
    contract_clause3_desc1: 'يلتزم الطرف الأول بتسليم المشروع خاليًا من العيوب البرمجية الجوهرية.',
    contract_clause3_desc2: 'يلتزم الطرف الثاني بتوفير كافة المعلومات والمحتوى اللازم في الوقت المحدد.',
    contract_clause3_desc3: 'يلتزم الطرف الثاني بسداد الدفعات المالية وفقاً للجدول الزمني المتفق عليه.',
    contract_clause4_title: 'البند الرابع: حقوق الملكية الفكرية',
    contract_clause4_desc: 'تنتقل جميع حقوق الملكية الفكرية للكود المصدري والتصاميم إلى الطرف الثاني فور سداد كامل المستحقات المالية للطرف الأول.',
    contract_clause5_title: 'البند الخامس: الخصوصية',
    contract_clause5_desc: 'يلتزم كلا الطرفين بالحفاظ على خصوصية المعلومات المتبادلة وعدم الإفصاح عنها لأي طرف ثالث دون موافقة كتابية مسبقة.',
    contract_party1_sign: 'الطرف الأول',
    contract_party2_sign: 'الطرف الثاني',
    contract_signature: 'التوقيع',
    download_contract: 'تحميل العقد',
    accept_contract: 'أوافق على',
    contract_agree: 'أقر بموافقتي التامة على شروط العقد والالتزامات المذكورة أعلاه',
    back_to_edit: 'رجوع للتعديل',
    confirm_and_pay: 'تأكيد والانتقال للدفع',
    secure_payment: 'بوابة الدفع الآمنة',
    enter_card_details: 'أدخل بيانات بطاقتك لإتمام عملية الشراء بأمان',
    card_name: 'الاسم على البطاقة',
    card_number: 'رقم البطاقة',
    expiry_date: 'تاريخ الانتهاء',
    cvv: 'رمز التحقق (CVV)',
    back: 'رجوع',
    pay_securely: 'دفع {price} $ بأمان',
    encrypted_payment: 'دفع مشفر 256-bit',
    success_title: 'تمت العملية بنجاح!',
    success_desc: 'شكراً لثقتك بنا، تم استلام طلبك وسيقوم فريقنا بالعمل عليه.',
    go_to_projects: 'انتقل لمشاريعي',
    fail_title: 'فشلت عملية الدفع',
    fail_desc: 'نعتذر، حدث خطأ أثناء معالجة الدفع. يرجى المحاولة مرة أخرى أو استخدام بطاقة أخرى.',
    retry: 'إعادة المحاولة',
    loading: 'جاري التحميل...',
    discount_code: 'كود الخصم',
    enter_discount_code: 'أدخل كود الخصم',
    apply: 'تطبيق',
    discount_code_hint: 'استخدم نقاط المكافآت للحصول على خصم إضافي',
    pay_securely_total: 'دفع {price} $ بأمان',
    price_before_discount: 'السعر قبل الخصم',
    price_after_discount: 'السعر بعد الخصم',
    final_total: 'الإجمالي النهائي',
    loyalty_points: 'نقاط المكافآت',
    point: 'نقطة',
    lang_ar: 'العربية',
    lang_en: 'English',
    lang_tr: 'Türkçe',
    turn_ideas: 'حول أفكارك إلى',
    reality: 'واقع',
    with_experts: 'مع أفضل الخبراء',
    home_subtitle: 'اختر الباقة المناسبة لمشروعك وابدأ التنفيذ فوراً مع ضمان الجودة والالتزام بالمواعيد.',
    browse_offers: 'تصفح الباقات',
    how_we_work: 'كيف نعمل؟',
    available_packages: 'الباقات المتاحة',
    all: 'الكل',
    design: 'تصميم',
    development: 'برمجة',
    marketing: 'تسويق',
    search_package: 'ابحث عن باقة...',
    most_popular: 'الأكثر طلباً',
    highest_rated: 'الأعلى تقييماً',
    price_low_high: 'السعر: من الأقل للأعلى',
    price_high_low: 'السعر: من الأعلى للأقل',
    order_now: 'اطلب الآن',
    add_compare: 'أضف للمقارنة',
    view_compare: 'عرض المقارنة',
    compare_packages: 'مقارنة الباقات',
    add_more_to_compare: 'أضف المزيد للمقارنة',
    select_another_package: 'اختر باقة أخرى لإضافتها للمقارنة',
    browse_packages: 'تصفح الباقات',
    choose_package: 'اختيار الباقة',
    feature: 'الميزة',
    price: 'السعر',
    rating: 'التقييم',
    features: 'المميزات',
    video_not_supported: 'متصفحك لا يدعم تشغيل الفيديو.',
    welcome_back: 'أهلاً بك مجدداً، إليك نظرة شاملة على أعمالك.',
    total_projects: 'إجمالي المشاريع',
    current_projects: 'المشاريع الحالية',
    completed_projects: 'المشاريع المكتملة',
    total_payments: 'إجمالي المدفوعات',
    in_progress_badge: 'قيد التنفيذ',
    deadline: 'الموعد النهائي',
    not_specified: 'غير محدد',
    current_stage: 'المرحلة الحالية',
    coding_testing: 'البرمجة والاختبار',
    budget: 'الميزانية',
    department: 'القسم المختص',
    web_dev: 'تطوير الويب',
    progress: 'تقدم العمل',
    tasks_completed: 'مهمة منجزة',
    tasks_remaining: 'مهام متبقية',
    manage_project: 'إدارة المشروع',
    no_active_projects: 'لا توجد مشاريع قيد التنفيذ',
    no_active_projects_desc: 'ليس لديك أي مشاريع جاري العمل عليها حالياً. يمكنك تصفح الباقات.',
    membership: 'عضوية',
    current_level: 'المستوى الحالي',
    collected_points: 'النقاط المجمعة',
    explore_rewards: 'استكشاف المكافآت',
    support_title: 'هل تواجه أي تحديات؟',
    support_desc: 'فريق الدعم الفني متاح على مدار الساعة لمساعدتك في إنجاز مشاريعك بأفضل صورة ممكنة.',
    talk_to_consultant: 'تحدث مع مستشارك الفني',
    loyalty_program: 'برنامج المكافآت',
    loyalty_desc: 'اكتشف المزايا والخصومات التي يمكنك الحصول عليها',
    how_to_earn: 'كيف تجمع النقاط؟',
    on_payment: 'عند الدفع',
    on_payment_desc: 'احصل على نقاط مقابل كل دولار تدفعه في مشاريعك وتضاف لرصيدك بعد اكتمال الدفع.',
    special_offers: 'عروض خاصة',
    special_offers_desc: 'استفد من العروض الخاصة التي تمنحك نقاط إضافية (مثال: 400 نقطة إضافية).',
    membership_levels: 'مستويات العضوية',
    bronze: 'برونزي',
    silver: 'فضي',
    gold: 'ذهبي',
    platinum: 'بلاتيني',
    your_current_level: '(مستواك الحالي)',
    bronze_points: 'من 0 إلى 1,000 نقطة',
    silver_points: 'من 1,001 إلى 3,000 نقطة',
    gold_points: 'من 3,001 إلى 5,000 نقطة',
    platinum_points: 'أكثر من 5,000 نقطة',
    bronze_benefit: 'عضوية أساسية',
    silver_benefit: 'كود خصم 5%',
    gold_benefit: 'كود خصم 10%',
    platinum_benefit: 'كود خصم 15%',
    got_it: 'حسناً، فهمت',
    track_projects: 'تتبع حالة مشاريعك ومراحل الإنجاز.',
    search_projects: 'ابحث في المشاريع...',
    pending: 'قيد الانتظار',
    in_progress: 'قيد التنفيذ',
    in_review: 'قيد المراجعة',
    completed: 'مكتمل',
    project_number: 'رقم المشروع:',
    started_on: 'بدأ في',
    completion_rate: 'نسبة الإنجاز',
    no_projects: 'لا توجد مشاريع حالياً',
    no_projects_desc: 'ابدأ بطلب باقتك الأولى الآن من الصفحة الرئيسية.',
    project_details_desc: 'تابع تفاصيل مشروعك والمراحل المنجزة.',
    project_status: 'حالة المشروع',
    project_timeline: 'الجدول الزمني للمشروع',
    project_files: 'ملفات المشروع',
    download: 'تحميل',
    financial_status: 'الحالة المالية',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    amount: 'المبلغ',
    invoice_date: 'تاريخ الفاتورة',
    pay_now: 'ادفع الآن',
    rate_project: 'تقييم المشروع',
    rate_desc: 'شاركنا رأيك في مستوى الخدمة المقدمة',
    quality: 'جودة العمل',
    speed: 'سرعة الإنجاز',
    communication: 'التواصل',
    commitment: 'الالتزام بالوقت',
    additional_comments: 'ملاحظات إضافية',
    recommend_us: 'هل تنصح بالتعامل معنا؟',
    yes: 'نعم',
    no: 'لا',
    submit_rating: 'إرسال التقييم',
    rating_thanks: 'شكراً لتقييمك! حصلت على 50 نقطة مكافأة وكوبون خصم 10%',
    invoices_desc: 'إدارة فواتيرك ومدفوعاتك السابقة والحالية.',
    search_invoices: 'ابحث في الفواتير...',
    invoice_number: 'رقم الفاتورة',
    status: 'الحالة',
    date: 'التاريخ',
    action: 'الإجراء',
    view_invoice: 'عرض الفاتورة',
    no_invoices: 'لا توجد فواتير حالياً',
    no_invoices_desc: 'لم يتم إصدار أي فواتير لمشاريعك حتى الآن.',
    pkg_design_name: 'باقة التصميم الأساسية',
    pkg_design_desc: 'تصميم هوية بصرية متكاملة للمشاريع الناشئة',
    pkg_design_f1: 'شعار واحد',
    pkg_design_f2: '3 تعديلات',
    pkg_design_f3: 'ملفات المصدر',
    pkg_dev_name: 'باقة البرمجة المتقدمة',
    pkg_dev_desc: 'تطوير متجر إلكتروني متكامل مع لوحة تحكم',
    pkg_dev_f1: 'متجر متكامل',
    pkg_dev_f2: 'دعم فني 3 أشهر',
    pkg_dev_f3: 'تكامل مع بوابات الدفع',
    pkg_marketing_name: 'باقة التسويق الشاملة',
    pkg_marketing_desc: 'إدارة حسابات التواصل الاجتماعي وحملات إعلانية',
    pkg_marketing_f1: 'إدارة 3 منصات',
    pkg_marketing_f2: '12 منشور شهرياً',
    pkg_marketing_f3: 'تقارير أداء',
    days: 'أيام',
    sar: '$',
    order_received: 'استلام الطلب',
    start_execution: 'بدء التنفيذ',
    phase_one_completed: 'انتهاء المرحلة الأولى',
    final_review: 'المراجعة النهائية',
    delivery: 'التسليم',
    overview: 'نظرة عامة',
    track_project: 'تتبع المشروع',
    files: 'الملفات',
    tech_chat: 'المحادثة التقنية',
    no_desc_available: 'لا يوجد وصف متاح لهذا المشروع.',
    responsible_team: 'الفريق المسؤول',
    team_members_count: '3 متخصصين يعملون على مشروعك',
    upload_new_file: 'رفع ملف جديد',
    two_days_ago: 'منذ يومين',
    tech_support: 'الدعم الفني للمشروع',
    online_now: 'متصل الآن',
    chat_msg_1: 'أهلاً بك! نحن نعمل حالياً على المرحلة الثانية من مشروعك. هل لديك أي استفسارات؟',
    chat_msg_2: 'شكراً لك، متى يتوقع الانتهاء من هذه المرحلة؟',
    type_message: 'اكتب رسالتك هنا...',
    quick_actions: 'إجراءات سريعة',
    request_edit: 'طلب تعديل',
    payment_status: 'حالة الدفع',
    all_invoices_paid: 'تم سداد جميع فواتير هذا المشروع بنجاح.',
    view_invoices: 'عرض الفواتير',
    rate_experience: 'قيم تجربتك معنا',
    project_completed_success: 'مبروك! تم اكتمال مشروعك بنجاح. رأيك يهمنا جداً.',
    execution_quality: 'جودة التنفيذ',
    describe_experience: 'وصف تجربتك',
    write_comment: 'اكتب تعليقك هنا...',
    recommend_service: 'هل تنصح بالخدمة؟',
    later: 'لاحقاً',
    invoices_tab: 'الفواتير',
    payment_history: 'سجل المدفوعات',
    contracts_documents: 'العقود والمستندات',
    project: 'المشروع',
    paid_status: 'مدفوعة',
    unpaid_status: 'غير مسددة',
    pay_invoice: 'سداد فاتورة',
    mada_card: 'بطاقة مدى',
    successful_transaction: 'عملية ناجحة',
    ecommerce_contract: 'عقد مشروع المتجر الإلكتروني',
    project_contract: 'عقد مشروع',
    sla_agreement: 'اتفاقية مستوى الخدمة (SLA)',
    agreement: 'اتفاقية',
    download_invoice: 'تحميل الفاتورة',
    commercial_contract: 'العقد التجاري',
    download_contract_btn: 'تحميل العقد',
    project_name_placeholder: 'مثال: تطبيق متجر إلكتروني',
    project_desc_placeholder: 'مثال: أحتاج تطبيق مشابه لتطبيق أوبر مع إضافة ميزة المحفظة الإلكترونية...',
    design_notes_placeholder: 'مثال: أفضل الألوان الفاتحة، وأريد تصميم عصري وبسيط...',
    company_name: 'شركة أبتك للأنظمة',
    company_address: 'الرياض، المملكة العربية السعودية',
    company_address_tr: 'إسطنبول، تركيا',
    vat_label: 'الرقم الضريبي',
    vat_number: '300012345600003',
    cr_label: 'السجل التجاري',
    cr_number: '1010123456',
    invoice_title: 'فاتورة ضريبية',
    bill_to: 'فاتورة إلى',
    invoice_details: 'تفاصيل الفاتورة',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    total: 'الإجمالي',
    vat: 'ضريبة القيمة المضافة (15%)',
    grand_total: 'الإجمالي النهائي',
    points_and_discounts: 'النقاط والخصومات',
    used_discount: 'الخصم المستخدم',
    earned_points: 'النقاط المكتسبة',
    available_discounts: 'الخصومات المتاحة',
    use_points_discount: 'استخدم {points} نقطة للحصول على خصم {discount}%',
    not_enough_points: 'رصيد النقاط غير كافي',
    apply_discount: 'تطبيق الخصم',
    discount_applied: 'تم تطبيق الخصم',
    remove_discount: 'إزالة',
    you_have_points: 'لديك {points} نقطة',
    points_balance: 'رصيد النقاط',
    project_status_in_review: 'قيد المراجعة',
    project_status_in_progress: 'قيد التنفيذ',
    project_status_completed: 'مكتمل',
    responsible_department: 'القسم المختص',
    request_revision: 'طلب تعديل',
    revision_reason: 'سبب التعديل',
    send_request: 'إرسال الطلب',
    technical_dept_files: 'ملفات القسم المختص',
    source_code_files: 'ملفات الكود المصدري',
    design_files: 'ملفات التصميم',
    database_files: 'ملفات قاعدة البيانات',
    other_files: 'ملفات أخرى',
    client_files: 'ملفات العميل',
    no_upload_allowed: 'لا يمكن رفع ملفات جديدة هنا',
    approve_stage: 'موافقة على المرحلة',
    request_stage_revision: 'طلب تعديل المرحلة',
    stage_suggestions: 'تطورات واقتراحات القسم التقني',
    stage_completed: 'مرحلة مكتملة',
    stage_pending: 'مرحلة منتظرة',
    stage_in_progress: 'مرحلة قيد التنفيذ',
    stage_revision: 'مرحلة قيد التعديل',
    last_seen: 'آخر ظهور',
    working_hours: 'ساعات العمل',
    seen: 'تمت الرؤية',
    unseen: 'لم تتم الرؤية',
    project_description_title: 'وصف المشروع',
    progress_percentage: 'نسبة الإنجاز',
    technical_chat: 'المحادثة التقنية',
    project_tracking: 'تتبع المشروع',
    files_tab: 'الملفات',
    overview_tab: 'نظرة عامة',
    revision_submitted: 'تم إرسال طلب التعديل بنجاح',
    stage_approved: 'تمت الموافقة على المرحلة',
    message_placeholder: 'اكتب رسالتك هنا...',
    send_message: 'إرسال',
    jan: 'يناير',
    feb: 'فبراير',
    mar: 'مارس',
    apr: 'أبريل',
    may: 'مايو',
    jun: 'يونيو',
    jul: 'يوليو',
    aug: 'أغسطس',
    sep: 'سبتمبر',
    oct: 'أكتوبر',
    nov: 'نوفمبر',
    dec: 'ديسمبر',
    date_today: 'الثلاثاء، 22 يوليو 2025',
    wd: 'ت.و',
    days_remaining: 'يوم متبقي',
    stage1_title: 'تحليل المتطلبات وتصميم الواجهات',
    stage1_suggestions: 'تم الانتهاء من تحليل المتطلبات الأساسية وتصميم واجهات المستخدم الأولية. نقترح إضافة نظام تقييم للمنتجات لزيادة ثقة العملاء.',
    stage2_title: 'تطوير قاعدة البيانات والنظام الخلفي',
    stage2_suggestions: 'نحن الآن في مرحلة بناء هيكل قاعدة البيانات. نقترح استخدام PostgreSQL لضمان استقرار البيانات الضخمة مستقبلاً.',
    stage3_title: 'تطوير واجهات المستخدم والربط',
    stage3_suggestions: 'هذه المرحلة ستبدأ فور الموافقة على المرحلة السابقة.'
  },
  EN: {
    login_title: 'Welcome back',
    login_subtitle: 'Please enter your details',
    signup_title: 'Create an account',
    signup_subtitle: 'Join us and start your projects',
    full_name: 'Full Name',
    first_name: 'First Name',
    last_name: 'Last Name',
    email_address: 'Email address',
    password: 'Password',
    confirm_password: 'Confirm Password',
    remember_me: 'Remember me',
    forgot_password: 'Forgot password',
    sign_in: 'Sign in',
    new_client: 'Don\'t have an account?',
    create_account: 'Create account',
    already_have_account: 'Already have an account?',
    phone_number: 'Phone number',
    verify_email: 'Please verify your email',
    password_reset_sent: 'Password reset link sent to your email',
    passwords_do_not_match: 'Passwords do not match',
    signup_failed: 'Signup failed',
    user_already_exists: 'User already exists',
    account_created_successfully: 'Account created successfully',
    login_failed: 'Login failed',
    invalid_credentials: 'Invalid credentials',
    enter_email_reset: 'Enter your email address and we will send you a link to reset your password.',
    cancel: 'Cancel',
    send_reset_link: 'Send Reset Link',
    tagline: 'Transform your ideas into reality with our company APPTECH SYSTEMS',
    validation_email_required: 'Please enter your email address',
    validation_email_invalid: 'Please enter a valid email address (e.g., example@domain.com)',
    validation_password_required: 'Please enter your password',
    validation_first_name_required: 'Please enter your first name',
    validation_last_name_required: 'Please enter your last name',
    validation_phone_required: 'Please enter your phone number',
    validation_password_length: 'Password must be at least 6 characters',
    faq: 'FAQ',
    faq_title: 'Frequently Asked Questions',
    faq_subtitle: 'Answers to the most common questions',
    faq_q1: 'How can I track my project progress?',
    faq_a1: 'You can track your project progress through your dashboard. You will find periodic updates and completed milestones.',
    faq_q2: 'What payment methods are accepted?',
    faq_a2: 'We accept credit cards (Visa, Mastercard) and bank transfers.',
    faq_q3: 'How can I contact support?',
    faq_a3: 'You can contact us via email or through the ticket system in your dashboard.',
    faq_q4: 'Can I modify project details after starting?',
    faq_a4: 'Yes, you can request modifications, but this may affect the timeline and cost depending on the scope.',
    faq_q5: 'Where can I find my invoices?',
    faq_a5: 'All invoices are available in the "Invoices & Payments" section and can be downloaded as PDF.',
    home: 'Home',
    dashboard: 'Dashboard',
    projects: 'My Projects',
    invoices: 'Invoices & Payments',
    settings: 'Settings',
    logout: 'Logout',
    logout_confirm: 'Are you sure you want to log out?',
    account_settings: 'Account Settings',
    manage_account_desc: 'Update your personal profile information and security settings',
    settings_updated: 'Account settings updated successfully',
    passwords_dont_match: 'New passwords do not match',
    personal_info: 'Personal Information',
    email: 'Email Address',
    phone: 'Phone Number',
    security: 'Security & Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_new_password: 'Confirm New Password',
    save_changes: 'Save Changes',
    language: 'Language',
    theme: 'Theme',
    user_name: 'Ahmed Mohammed',
    user_role: 'Client',
    light_mode: 'Light',
    dark_mode: 'Dark',
    order_completion: 'Order Completion',
    back_home: 'Back to Home',
    project_details: 'Project Details',
    confirm_order: 'Confirm Order',
    payment: 'Payment',
    project_name: 'Project Name',
    project_desc: 'Project Description',
    design_notes: 'Design Notes (Optional)',
    upload_files: 'Upload Design Files (Optional)',
    drag_drop: 'Drag and drop files here or click to select',
    upload_hint: 'You can upload images, PDFs, or ZIP files',
    add_more_files: 'Add more files',
    next_step: 'Next Step',
    order_summary: 'Order Summary',
    selected_package: 'Selected Package',
    execution_time: 'Execution Time',
    total_cost: 'Total Cost',
    working_days: 'working days',
    currency: '$',
    contract_title: 'Terms and Conditions & Software Services Agreement',
    contract_doc_title: 'Technical Services Contract',
    contract_doc_no: 'Document No:',
    contract_intro: 'This contract is made between:',
    contract_party1: 'First Party (Service Provider):',
    contract_party1_name: 'APPTECH SYSTEMS',
    contract_party2: 'Second Party (Client):',
    contract_party2_name: 'Project Owner',
    contract_clause1_title: 'Clause 1: Subject of the Contract',
    contract_clause1_desc: 'The First Party commits to developing and implementing the agreed software project according to the specifications and requirements provided by the Second Party, which are considered an integral part of this contract.',
    contract_clause2_title: 'Clause 2: Scope of Work',
    contract_clause2_desc: 'The scope of work includes designing and developing user interfaces, database programming, and integrating necessary APIs for the system to function fully as described in the requirements document.',
    contract_clause3_title: 'Clause 3: Obligations of the Parties',
    contract_clause3_desc1: 'The First Party commits to delivering the project free of material software defects.',
    contract_clause3_desc2: 'The Second Party commits to providing all necessary information and content on time.',
    contract_clause3_desc3: 'The Second Party commits to paying financial installments according to the agreed schedule.',
    contract_clause4_title: 'Clause 4: Intellectual Property Rights',
    contract_clause4_desc: 'All intellectual property rights for the source code and designs transfer to the Second Party upon full payment of financial dues to the First Party.',
    contract_clause5_title: 'Clause 5: Privacy',
    contract_clause5_desc: 'Both parties commit to maintaining the privacy of exchanged information and not disclosing it to any third party without prior written consent.',
    contract_party1_sign: 'First Party',
    contract_party2_sign: 'Second Party',
    contract_signature: 'Signature',
    download_contract: 'Download Contract',
    accept_contract: 'I agree to the',
    contract_agree: 'I fully agree to the terms and obligations stated above',
    back_to_edit: 'Back to Edit',
    confirm_and_pay: 'Confirm & Proceed to Payment',
    secure_payment: 'Secure Payment Gateway',
    enter_card_details: 'Enter your card details to complete the purchase securely',
    card_name: 'Name on Card',
    card_number: 'Card Number',
    expiry_date: 'Expiry Date',
    cvv: 'CVV',
    back: 'Back',
    pay_securely: 'Pay {price} $ Securely',
    encrypted_payment: '256-bit Encrypted Payment',
    success_title: 'Transaction Successful!',
    success_desc: 'Thank you for your trust. Your order has been received and our team will start working on it.',
    go_to_projects: 'Go to My Projects',
    fail_title: 'Payment Failed',
    fail_desc: 'Sorry, an error occurred while processing your payment. Please try again or use a different card.',
    retry: 'Retry',
    loading: 'Loading...',
    discount_code: 'Discount Code',
    enter_discount_code: 'Enter discount code',
    apply: 'Apply',
    discount_code_hint: 'Use reward points to get an extra discount',
    pay_securely_total: 'Pay {price} $ Securely',
    price_before_discount: 'Price Before Discount',
    price_after_discount: 'Price After Discount',
    final_total: 'Final Total',
    loyalty_points: 'Reward Points',
    point: 'Point',
    lang_ar: 'Arabic',
    lang_en: 'English',
    lang_tr: 'Turkish',
    turn_ideas: 'Turn your ideas into',
    reality: 'reality',
    with_experts: 'with the best experts',
    home_subtitle: 'Choose the right package for your project and start execution immediately with guaranteed quality and punctuality.',
    browse_offers: 'Browse Packages',
    how_we_work: 'How we work?',
    available_packages: 'Available Packages',
    all: 'All',
    design: 'Design',
    development: 'Development',
    marketing: 'Marketing',
    search_package: 'Search for a package...',
    most_popular: 'Most Popular',
    highest_rated: 'Highest Rated',
    price_low_high: 'Price: Low to High',
    price_high_low: 'Price: High to Low',
    order_now: 'Order Now',
    add_compare: 'Add to Compare',
    view_compare: 'View Comparison',
    compare_packages: 'Compare Packages',
    add_more_to_compare: 'Add more to compare',
    select_another_package: 'Select another package to compare',
    browse_packages: 'Browse Packages',
    choose_package: 'Choose Package',
    feature: 'Feature',
    price: 'Price',
    rating: 'Rating',
    features: 'Features',
    video_not_supported: 'Your browser does not support video playback.',
    welcome_back: 'Welcome back, here is a comprehensive overview of your business.',
    total_projects: 'Total Projects',
    current_projects: 'Current Projects',
    completed_projects: 'Completed Projects',
    total_payments: 'Total Payments',
    in_progress_badge: 'In Progress',
    deadline: 'Deadline',
    not_specified: 'Not Specified',
    current_stage: 'Current Stage',
    coding_testing: 'Coding & Testing',
    budget: 'Budget',
    department: 'Department',
    web_dev: 'Web Development',
    progress: 'Progress',
    tasks_completed: 'tasks completed',
    tasks_remaining: 'tasks remaining',
    manage_project: 'Manage Project',
    no_active_projects: 'No Active Projects',
    no_active_projects_desc: 'You have no projects currently in progress. You can browse packages.',
    membership: 'Membership',
    current_level: 'Current Level',
    collected_points: 'Collected Points',
    explore_rewards: 'Explore Rewards',
    support_title: 'Facing any challenges?',
    support_desc: 'Our technical support team is available 24/7 to help you complete your projects in the best possible way.',
    talk_to_consultant: 'Talk to your technical consultant',
    loyalty_program: 'Rewards Program',
    loyalty_desc: 'Discover the benefits and discounts you can get',
    how_to_earn: 'How to earn points?',
    on_payment: 'On Payment',
    on_payment_desc: 'Get points for every riyal you pay for your projects, added to your balance after payment completion.',
    special_offers: 'Special Offers',
    special_offers_desc: 'Take advantage of special offers that give you extra points (e.g., 400 extra points).',
    membership_levels: 'Membership Levels',
    bronze: 'Bronze',
    silver: 'Silver',
    gold: 'Gold',
    platinum: 'Platinum',
    your_current_level: '(Your current level)',
    bronze_points: 'From 0 to 1,000 points',
    silver_points: 'From 1,001 to 3,000 points',
    gold_points: 'From 3,001 to 5,000 points',
    platinum_points: 'More than 5,000 points',
    bronze_benefit: 'Basic Membership',
    silver_benefit: '5% Discount Code',
    gold_benefit: '10% Discount Code',
    platinum_benefit: '15% Discount Code',
    got_it: 'Got it',
    track_projects: 'Track the status of your projects and completion stages.',
    search_projects: 'Search projects...',
    pending: 'Pending',
    in_progress: 'In Progress',
    in_review: 'In Review',
    completed: 'Completed',
    project_number: 'Project Number:',
    started_on: 'Started on',
    completion_rate: 'Completion Rate',
    no_projects: 'No Projects Currently',
    no_projects_desc: 'Start by ordering your first package now from the home page.',
    project_details_desc: 'Follow your project details and completed stages.',
    project_status: 'Project Status',
    project_timeline: 'Project Timeline',
    project_files: 'Project Files',
    download: 'Download',
    financial_status: 'Financial Status',
    paid: 'Paid',
    unpaid: 'Unpaid',
    amount: 'Amount',
    invoice_date: 'Invoice Date',
    pay_now: 'Pay Now',
    rate_project: 'Rate Project',
    rate_desc: 'Share your opinion on the level of service provided',
    quality: 'Quality of Work',
    speed: 'Speed of Execution',
    communication: 'Communication',
    commitment: 'Time Commitment',
    additional_comments: 'Additional Comments',
    recommend_us: 'Would you recommend us?',
    yes: 'Yes',
    no: 'No',
    submit_rating: 'Submit Rating',
    rating_thanks: 'Thank you for your rating! You got 50 reward points and a 10% discount coupon',
    invoices_desc: 'Manage your past and current invoices and payments.',
    search_invoices: 'Search invoices...',
    invoice_number: 'Invoice Number',
    status: 'Status',
    date: 'Date',
    action: 'Action',
    view_invoice: 'View Invoice',
    no_invoices: 'No Invoices Currently',
    no_invoices_desc: 'No invoices have been issued for your projects yet.',
    pkg_design_name: 'Basic Design Package',
    pkg_design_desc: 'Complete visual identity design for startups',
    pkg_design_f1: 'One Logo',
    pkg_design_f2: '3 Revisions',
    pkg_design_f3: 'Source Files',
    pkg_dev_name: 'Advanced Development Package',
    pkg_dev_desc: 'Full e-commerce development with dashboard',
    pkg_dev_f1: 'Full Store',
    pkg_dev_f2: '3 Months Support',
    pkg_dev_f3: 'Payment Gateway Integration',
    pkg_marketing_name: 'Comprehensive Marketing Package',
    pkg_marketing_desc: 'Social media management and ad campaigns',
    pkg_marketing_f1: 'Manage 3 Platforms',
    pkg_marketing_f2: '12 Posts Monthly',
    pkg_marketing_f3: 'Performance Reports',
    days: 'Days',
    sar: '$',
    order_received: 'Order Received',
    start_execution: 'Start Execution',
    phase_one_completed: 'Phase One Completed',
    final_review: 'Final Review',
    delivery: 'Delivery',
    overview: 'Overview',
    track_project: 'Track Project',
    files: 'Files',
    tech_chat: 'Technical Chat',
    no_desc_available: 'No description available for this project.',
    responsible_team: 'Responsible Team',
    team_members_count: '3 specialists working on your project',
    upload_new_file: 'Upload New File',
    two_days_ago: '2 days ago',
    tech_support: 'Project Technical Support',
    online_now: 'Online Now',
    chat_msg_1: 'Welcome! We are currently working on the second phase of your project. Do you have any questions?',
    chat_msg_2: 'Thank you, when is this phase expected to be completed?',
    type_message: 'Type your message here...',
    quick_actions: 'Quick Actions',
    request_edit: 'Request Edit',
    payment_status: 'Payment Status',
    all_invoices_paid: 'All invoices for this project have been paid successfully.',
    view_invoices: 'View Invoices',
    rate_experience: 'Rate your experience with us',
    project_completed_success: 'Congratulations! Your project has been completed successfully. Your opinion is very important to us.',
    execution_quality: 'Execution Quality',
    describe_experience: 'Describe your experience',
    write_comment: 'Write your comment here...',
    recommend_service: 'Would you recommend the service?',
    later: 'Later',
    invoices_tab: 'Invoices',
    payment_history: 'Payment History',
    contracts_documents: 'Contracts & Documents',
    project: 'Project',
    paid_status: 'Paid',
    unpaid_status: 'Unpaid',
    pay_invoice: 'Pay Invoice',
    mada_card: 'Mada Card',
    successful_transaction: 'Successful Transaction',
    ecommerce_contract: 'E-commerce Project Contract',
    project_contract: 'Project Contract',
    sla_agreement: 'Service Level Agreement (SLA)',
    agreement: 'Agreement',
    download_invoice: 'Download Invoice',
    commercial_contract: 'Commercial Contract',
    download_contract_btn: 'Download Contract',
    project_name_placeholder: 'Example: E-commerce App',
    project_desc_placeholder: 'Example: I need an app similar to Uber with an added e-wallet feature...',
    design_notes_placeholder: 'Example: I prefer light colors, and I want a modern and simple design...',
    company_name: 'AppTech Systems',
    company_address: 'Riyadh, Saudi Arabia',
    company_address_tr: 'Istanbul, Turkey',
    vat_label: 'VAT',
    vat_number: '300012345600003',
    cr_label: 'CR',
    cr_number: '1010123456',
    invoice_title: 'Tax Invoice',
    bill_to: 'Bill To',
    invoice_details: 'Invoice Details',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    vat: 'VAT (15%)',
    grand_total: 'Grand Total',
    points_and_discounts: 'Points and Discounts',
    used_discount: 'Used Discount',
    earned_points: 'Earned Points',
    available_discounts: 'Available Discounts',
    use_points_discount: 'Use {points} points to get {discount}% discount',
    not_enough_points: 'Insufficient points balance',
    apply_discount: 'Apply Discount',
    discount_applied: 'Discount Applied',
    remove_discount: 'Remove',
    you_have_points: 'You have {points} points',
    points_balance: 'Points Balance',
    project_status_in_review: 'In Review',
    project_status_in_progress: 'In Progress',
    project_status_completed: 'Completed',
    responsible_department: 'Responsible Department',
    request_revision: 'Request Revision',
    revision_reason: 'Revision Reason',
    send_request: 'Send Request',
    technical_dept_files: 'Technical Dept Files',
    source_code_files: 'Source Code Files',
    design_files: 'Design Files',
    database_files: 'Database Files',
    other_files: 'Other Files',
    client_files: 'Client Files',
    no_upload_allowed: 'New uploads are not allowed here',
    approve_stage: 'Approve Stage',
    request_stage_revision: 'Request Stage Revision',
    stage_suggestions: 'Technical Dept Developments & Suggestions',
    stage_completed: 'Stage Completed',
    stage_pending: 'Stage Pending',
    stage_in_progress: 'Stage In Progress',
    stage_revision: 'Stage Under Revision',
    last_seen: 'Last Seen',
    working_hours: 'Working Hours',
    seen: 'Seen',
    unseen: 'Unseen',
    project_description_title: 'Project Description',
    progress_percentage: 'Progress Percentage',
    technical_chat: 'Technical Chat',
    project_tracking: 'Project Tracking',
    files_tab: 'Files',
    overview_tab: 'Overview',
    revision_submitted: 'Revision request submitted successfully',
    stage_approved: 'Stage approved successfully',
    message_placeholder: 'Type your message here...',
    send_message: 'Send',
    jan: 'Jan',
    feb: 'Feb',
    mar: 'Mar',
    apr: 'Apr',
    may: 'May',
    jun: 'Jun',
    jul: 'Jul',
    aug: 'Aug',
    sep: 'Sep',
    oct: 'Oct',
    nov: 'Nov',
    dec: 'Dec',
    date_today: 'Tuesday, July 22, 2025',
    wd: 'WD',
    start_date: 'Started on',
    technical_dept: 'Technical Department',
    web_mobile_dev: 'Web and Mobile App Development Section',
    days_remaining: 'days remaining',
    stage1_title: 'Requirements Analysis & UI Design',
    stage1_suggestions: 'Basic requirements analysis and initial user interfaces design are completed. We suggest adding a product rating system to increase customer trust.',
    stage2_title: 'Database & Backend Development',
    stage2_suggestions: 'We are currently building the database structure. We suggest using PostgreSQL to ensure massive data stability in the future.',
    stage3_title: 'Frontend Development & API Integration',
    stage3_suggestions: 'This stage will begin immediately upon approval of the previous stage.'
  },
  TR: {
    login_title: 'Tekrar hoş geldiniz',
    login_subtitle: 'Lütfen bilgilerinizi girin',
    signup_title: 'Hesap oluştur',
    signup_subtitle: 'Bize katılın ve projelerinize başlayın',
    full_name: 'Ad Soyad',
    first_name: 'Ad',
    last_name: 'Soyad',
    email_address: 'E-posta adresi',
    password: 'Şifre',
    confirm_password: 'Şifreyi onayla',
    remember_me: 'Beni hatırla',
    forgot_password: 'Şifremi unuttum',
    sign_in: 'Giriş yap',
    new_client: 'Hesabınız yok mu?',
    create_account: 'Hesap oluştur',
    already_have_account: 'Zaten bir hesabınız var mı?',
    phone_number: 'Telefon numarası',
    verify_email: 'Lütfen e-postanızı doğrulayın',
    password_reset_sent: 'Şifre sıfırlama bağlantısı e-postanıza gönderildi',
    passwords_do_not_match: 'Şifreler eşleşmiyor',
    signup_failed: 'Hesap oluşturma başarısız',
    user_already_exists: 'Kullanıcı zaten mevcut',
    account_created_successfully: 'Hesap başarıyla oluşturuldu',
    login_failed: 'Giriş başarısız',
    invalid_credentials: 'Geçersiz kimlik bilgileri',
    enter_email_reset: 'E-posta adresinizi girin, şifrenizi sıfırlamanız için size bir bağlantı gönderelim.',
    cancel: 'İptal',
    send_reset_link: 'Sıfırlama Bağlantısı Gönder',
    tagline: 'Fikirlerinizi şirketimiz APPTECH SYSTEMS ile gerçeğe dönüştürün',
    validation_email_required: 'Lütfen e-posta adresinizi girin',
    validation_email_invalid: 'Lütfen geçerli bir e-posta adresi girin (örn: example@domain.com)',
    validation_password_required: 'Lütfen şifrenizi girin',
    validation_first_name_required: 'Lütfen adınızı girin',
    validation_last_name_required: 'Lütfen soyadınızı girin',
    validation_phone_required: 'Lütfen telefon numaranızı girin',
    validation_password_length: 'Şifre en az 6 karakter olmalıdır',
    faq: 'Sıkça Sorulan Sorular',
    faq_title: 'Sıkça Sorulan Sorular',
    faq_subtitle: 'En yaygın soruların cevapları',
    faq_q1: 'Proje ilerlememi nasıl takip edebilirim?',
    faq_a1: 'Proje ilerlemenizi kontrol panelinizden takip edebilirsiniz. Düzenli güncellemeler ve tamamlanan aşamaları bulacaksınız.',
    faq_q2: 'Hangi ödeme yöntemleri kabul ediliyor?',
    faq_a2: 'Kredi kartları (Visa, Mastercard) ve banka havalesi kabul ediyoruz.',
    faq_q3: 'Destek ekibiyle nasıl iletişime geçebilirim?',
    faq_a3: 'Bize e-posta yoluyla veya kontrol panelindeki bilet sistemi üzerinden ulaşabilirsiniz.',
    faq_q4: 'Başladıktan sonra proje detaylarını değiştirebilir miyim?',
    faq_a4: 'Evet, değişiklik talep edebilirsiniz, ancak bu kapsamına bağlı olarak zaman çizelgesini ve maliyeti etkileyebilir.',
    faq_q5: 'Faturalarımı nerede bulabilirim?',
    faq_a5: 'Tüm faturalar "Faturalar ve Ödemeler" bölümünde mevcuttur ve PDF olarak indirilebilir.',
    home: 'Ana Sayfa',
    dashboard: 'Kontrol Paneli',
    projects: 'Projelerim',
    invoices: 'Faturalar ve Ödemeler',
    settings: 'Ayarlar',
    logout: 'Çıkış Yap',
    logout_confirm: 'Çıkış yapmak istediğinizden emin misiniz?',
    account_settings: 'Hesap Ayarları',
    manage_account_desc: 'Kişisel profil bilgilerinizi ve güvenlik ayarlarınızı güncelleyin',
    settings_updated: 'Hesap ayarları başarıyla güncellendi',
    passwords_dont_match: 'Yeni şifreler eşleşmiyor',
    personal_info: 'Kişisel Bilgiler',
    email: 'E-posta Adresi',
    phone: 'Telefon Numarası',
    security: 'Güvenlik ve Şifre',
    current_password: 'Mevcut Şifre',
    new_password: 'Yeni Şifre',
    confirm_new_password: 'Yeni Şifreyi Onayla',
    save_changes: 'Değişiklikleri Kaydet',
    language: 'Dil',
    theme: 'Tema',
    user_name: 'Ahmed Mohammed',
    user_role: 'Müşteri',
    light_mode: 'Açık',
    dark_mode: 'Koyu',
    order_completion: 'Siparişi Tamamla',
    back_home: 'Ana Sayfaya Dön',
    project_details: 'Proje Detayları',
    confirm_order: 'Siparişi Onayla',
    payment: 'Ödeme',
    project_name: 'Proje Adı',
    project_desc: 'Proje Açıklaması',
    design_notes: 'Tasarım Notları (İsteğe Bağlı)',
    upload_files: 'Tasarım Dosyalarını Yükle (İsteğe Bağlı)',
    drag_drop: 'Dosyaları buraya sürükleyin veya seçmek için tıklayın',
    upload_hint: 'Resim, PDF veya ZIP dosyaları yükleyebilirsiniz',
    add_more_files: 'Daha fazla dosya ekle',
    next_step: 'Sonraki Adım',
    order_summary: 'Sipariş Özeti',
    selected_package: 'Seçilen Paket',
    execution_time: 'Teslim Süresi',
    total_cost: 'Toplam Maliyet',
    working_days: 'iş günü',
    currency: '$',
    contract_title: 'Şartlar ve Koşullar ve Yazılım Hizmetleri Sözleşmesi',
    contract_doc_title: 'Teknik Hizmetler Sözleşmesi',
    contract_doc_no: 'Belge No:',
    contract_intro: 'Bu sözleşme aşağıdakiler arasında yapılmıştır:',
    contract_party1: 'Birinci Taraf (Hizmet Sağlayıcı):',
    contract_party1_name: 'APPTECH SYSTEMS',
    contract_party2: 'İkinci Taraf (Müşteri):',
    contract_party2_name: 'Proje Sahibi',
    contract_clause1_title: 'Madde 1: Sözleşmenin Konusu',
    contract_clause1_desc: 'Birinci Taraf, İkinci Tarafça sağlanan ve bu sözleşmenin ayrılmaz bir parçası olarak kabul edilen spesifikasyonlara ve gereksinimlere göre anlaşılan yazılım projesini geliştirmeyi ve uygulamayı taahhüt eder.',
    contract_clause2_title: 'Madde 2: İşin Kapsamı',
    contract_clause2_desc: 'İşin kapsamı, kullanıcı arayüzlerinin tasarlanması ve geliştirilmesi, veritabanı programlaması ve sistemin gereksinimler belgesinde açıklandığı gibi tam olarak çalışması için gerekli API\'lerin entegre edilmesini içerir.',
    contract_clause3_title: 'Madde 3: Tarafların Yükümlülükleri',
    contract_clause3_desc1: 'Birinci Taraf, projeyi önemli yazılım kusurlarından arınmış olarak teslim etmeyi taahhüt eder.',
    contract_clause3_desc2: 'İkinci Taraf, gerekli tüm bilgi ve içeriği zamanında sağlamayı taahhüt eder.',
    contract_clause3_desc3: 'İkinci Taraf, anlaşılan programa göre mali taksitleri ödemeyi taahhüt eder.',
    contract_clause4_title: 'Madde 4: Fikri Mülkiyet Hakları',
    contract_clause4_desc: 'Kaynak kodu ve tasarımlar için tüm fikri mülkiyet hakları, Birinci Tarafa olan mali borçların tam olarak ödenmesi üzerine İkinci Tarafa geçer.',
    contract_clause5_title: 'Madde 5: Gizlilik ve Veri Koruma',
    contract_clause5_desc: 'Her iki taraf da, paylaşılan bilgilerin gizliliğini ve özel hayatını korumayı ve önceden yazılı izin olmaksızın herhangi bir üçüncü tarafa ifşa etmemeyi taahhüt eder.',
    contract_party1_sign: 'Birinci Taraf',
    contract_party2_sign: 'İkinci Taraf',
    contract_signature: 'İmza',
    download_contract: 'Sözleşmeyi İndir',
    accept_contract: 'Kabul ediyorum:',
    contract_agree: 'Yukarıda belirtilen şartları ve yükümlülükleri tamamen kabul ediyorum',
    back_to_edit: 'Düzenlemeye Dön',
    confirm_and_pay: 'Onayla ve Ödemeye Geç',
    secure_payment: 'Güvenli Ödeme Geçidi',
    enter_card_details: 'Satın alma işlemini güvenle tamamlamak için kart bilgilerinizi girin',
    card_name: 'Kart Üzerindeki İsim',
    card_number: 'Kart Numarası',
    expiry_date: 'Son Kullanma Tarihi',
    cvv: 'CVV',
    back: 'Geri',
    pay_securely: '{price} $ Güvenle Öde',
    encrypted_payment: '256-bit Şifreli Ödeme',
    success_title: 'İşlem Başarılı!',
    success_desc: 'Güveniniz için teşekkür ederiz. Siparişiniz alındı ve ekibimiz üzerinde çalışmaya başlayacak.',
    go_to_projects: 'Projelerime Git',
    fail_title: 'Ödeme Başarısız',
    fail_desc: 'Üzgünüz, ödemeniz işlenirken bir hata oluştu. Lütfen tekrar deneyin veya farklı bir kart kullanın.',
    retry: 'Tekrar Dene',
    loading: 'Yükleniyor...',
    discount_code: 'İndirim Kodu',
    enter_discount_code: 'İndirim kodunu girin',
    apply: 'Uygula',
    discount_code_hint: 'Ekstra indirim almak için ödül puanlarını kullanın',
    pay_securely_total: '{price} $ Güvenle Öde',
    price_before_discount: 'İndirim Öncesi Fiyat',
    price_after_discount: 'İndirim Sonrası Fiyat',
    final_total: 'Genel Toplam',
    loyalty_points: 'Ödül Puanları',
    point: 'Puan',
    lang_ar: 'Arapça',
    lang_en: 'İngilizce',
    lang_tr: 'Türkçe',
    turn_ideas: 'Fikirlerinizi',
    reality: 'gerçeğe',
    with_experts: 'en iyi uzmanlarla dönüştürün',
    home_subtitle: 'Projeniz için doğru paketi seçin ve garantili kalite ve zamanındalık ile hemen uygulamaya başlayın.',
    browse_offers: 'Paketlere Göz At',
    how_we_work: 'Nasıl çalışıyoruz?',
    available_packages: 'Mevcut Paketler',
    all: 'Tümü',
    design: 'Tasarım',
    development: 'Geliştirme',
    marketing: 'Pazarlama',
    search_package: 'Paket ara...',
    most_popular: 'En Popüler',
    highest_rated: 'En Yüksek Puanlı',
    price_low_high: 'Fiyat: Düşükten Yükseğe',
    price_high_low: 'Fiyat: Yüksekten Düşüğe',
    order_now: 'Şimdi Sipariş Ver',
    add_compare: 'Karşılaştırmaya Ekle',
    view_compare: 'Karşılaştırmayı Görüntüle',
    compare_packages: 'Paketleri Karşılaştır',
    add_more_to_compare: 'Karşılaştırmak için daha fazla ekle',
    select_another_package: 'Karşılaştırmak için başka bir paket seçin',
    browse_packages: 'Paketlere Göz At',
    choose_package: 'Paketi Seç',
    feature: 'Özellik',
    price: 'Fiyat',
    rating: 'Değerlendirme',
    features: 'Özellikler',
    video_not_supported: 'Tarayıcınız video oynatmayı desteklemiyor.',
    welcome_back: 'Tekrar hoş geldiniz, işte işinize kapsamlı bir bakış.',
    total_projects: 'Toplam Proje',
    current_projects: 'Mevcut Projeler',
    completed_projects: 'Tamamlanan Projeler',
    total_payments: 'Toplam Ödemeler',
    in_progress_badge: 'Devam Ediyor',
    deadline: 'Son Teslim Tarihi',
    not_specified: 'Belirtilmemiş',
    current_stage: 'Mevcut Aşama',
    coding_testing: 'Kodlama ve Test',
    budget: 'Bütçe',
    department: 'Departman',
    web_dev: 'Web Geliştirme',
    progress: 'İlerleme',
    tasks_completed: 'görev tamamlandı',
    tasks_remaining: 'görev kaldı',
    manage_project: 'Projeyi Yönet',
    no_active_projects: 'Aktif Proje Yok',
    no_active_projects_desc: 'Şu anda devam eden projeniz yok. Paketlere göz atabilirsiniz.',
    membership: 'Üyelik',
    current_level: 'Mevcut Seviye',
    collected_points: 'Toplanan Puanlar',
    explore_rewards: 'Ödülleri Keşfet',
    support_title: 'Herhangi bir zorlukla mı karşılaşıyorsunuz?',
    support_desc: 'Teknik destek ekibimiz, projelerinizi en iyi şekilde tamamlamanıza yardımcı olmak için 7/24 hizmetinizdedir.',
    talk_to_consultant: 'Teknik danışmanınızla konuşun',
    loyalty_program: 'Ödül Programı',
    loyalty_desc: 'Alabileceğiniz avantajları ve indirimleri keşfedin',
    how_to_earn: 'Nasıl puan kazanılır?',
    on_payment: 'Ödeme Yapıldığında',
    on_payment_desc: 'Projeleriniz için ödediğiniz her riyal için puan kazanın, ödeme tamamlandıktan sonra bakiyenize eklenir.',
    special_offers: 'Özel Teklifler',
    special_offers_desc: 'Size ekstra puan kazandıran özel tekliflerden yararlanın (ör. 400 ekstra puan).',
    membership_levels: 'Üyelik Seviyeleri',
    bronze: 'Bronz',
    silver: 'Gümüş',
    gold: 'Altın',
    platinum: 'Platin',
    your_current_level: '(Mevcut seviyeniz)',
    bronze_points: '0 ile 1.000 puan arası',
    silver_points: '1.001 ile 3.000 puan arası',
    gold_points: '3.001 ile 5.000 puan arası',
    platinum_points: '5.000 puandan fazla',
    bronze_benefit: 'Temel Üyelik',
    silver_benefit: '%5 İndirim Kodu',
    gold_benefit: '%10 İndirim Kodu',
    platinum_benefit: '%15 İndirim Kodu',
    got_it: 'Anladım',
    track_projects: 'Projelerinizin durumunu ve tamamlanma aşamalarını takip edin.',
    search_projects: 'Proje ara...',
    pending: 'Bekliyor',
    in_progress: 'Devam Ediyor',
    in_review: 'İncelemede',
    completed: 'Tamamlandı',
    project_number: 'Proje Numarası:',
    started_on: 'Başlangıç',
    completion_rate: 'Tamamlanma Oranı',
    no_projects: 'Şu Anda Proje Yok',
    no_projects_desc: 'İlk paketinizi ana sayfadan sipariş ederek başlayın.',
    project_details_desc: 'Proje detaylarınızı ve tamamlanan aşamaları takip edin.',
    project_status: 'Proje Durumu',
    project_timeline: 'Proje Zaman Çizelgesi',
    project_files: 'Proje Dosyaları',
    download: 'İndir',
    financial_status: 'Finansal Durum',
    paid: 'Ödendi',
    unpaid: 'Ödenmedi',
    amount: 'Tutar',
    invoice_date: 'Fatura Tarihi',
    pay_now: 'Şimdi Öde',
    rate_project: 'Projeyi Değerlendir',
    rate_desc: 'Sunulan hizmet seviyesi hakkındaki görüşlerinizi paylaşın',
    quality: 'İş Kalitesi',
    speed: 'Uygulama Hızı',
    communication: 'İletişim',
    commitment: 'Zaman Taahhüdü',
    additional_comments: 'Ek Yorumlar',
    recommend_us: 'Bizi tavsiye eder misiniz?',
    yes: 'Evet',
    no: 'Hayır',
    submit_rating: 'Değerlendirmeyi Gönder',
    rating_thanks: 'Değerlendirmeniz için teşekkürler! 50 ödül puanı ve %10 indirim kuponu kazandınız',
    invoices_desc: 'Geçmiş ve mevcut faturalarınızı ve ödemelerinizi yönetin.',
    search_invoices: 'Fatura ara...',
    invoice_number: 'Fatura Numarası',
    status: 'Durum',
    date: 'Tarih',
    action: 'İşlem',
    view_invoice: 'Faturayı Görüntüle',
    no_invoices: 'Şu Anda Fatura Yok',
    no_invoices_desc: 'Projeleriniz için henüz fatura kesilmedi.',
    pkg_design_name: 'Temel Tasarım Paketi',
    pkg_design_desc: 'Girişimler için tam görsel kimlik tasarimi',
    pkg_design_f1: 'Bir Logo',
    pkg_design_f2: '3 Revizyon',
    pkg_design_f3: 'Kaynak Dosyalar',
    pkg_dev_name: 'Gelişmiş Geliştirme Paketi',
    pkg_dev_desc: 'Kontrol panelli tam e-ticaret geliştirme',
    pkg_dev_f1: 'Tam Mağaza',
    pkg_dev_f2: '3 Ay Destek',
    pkg_dev_f3: 'Ödeme Geçidi Entegrasyonu',
    pkg_marketing_name: 'Kapsamlı Pazarlama Paketi',
    pkg_marketing_desc: 'Sosyal medya yönetimi ve reklam kampanyaları',
    pkg_marketing_f1: '3 Platform Yönetimi',
    pkg_marketing_f2: 'Aylık 12 Gönderi',
    pkg_marketing_f3: 'Performans Raporları',
    days: 'Gün',
    sar: '$',
    order_received: 'Sipariş Alındı',
    start_execution: 'Uygulamaya Başla',
    phase_one_completed: 'Birinci Aşama Tamamlandı',
    final_review: 'Son İnceleme',
    delivery: 'Teslimat',
    overview: 'Genel Bakış',
    track_project: 'Projeyi Takip Et',
    files: 'Dosyalar',
    tech_chat: 'Teknik Sohbet',
    no_desc_available: 'Bu proje için açıklama bulunmuyor.',
    responsible_team: 'Sorumlu Ekip',
    team_members_count: 'Projenizde çalışan 3 uzman',
    upload_new_file: 'Yeni Dosya Yükle',
    two_days_ago: '2 gün önce',
    tech_support: 'Proje Teknik Desteği',
    online_now: 'Şu An Çevrimiçi',
    chat_msg_1: 'Hoş geldiniz! Şu anda projenizin ikinci aşaması üzerinde çalışıyoruz. Herhangi bir sorunuz var mı?',
    chat_msg_2: 'Teşekkür ederim, bu aşamanın ne zaman tamamlanması bekleniyor?',
    type_message: 'Mesajınızı buraya yazın...',
    quick_actions: 'Hızlı İşlemler',
    request_edit: 'Düzenleme İste',
    payment_status: 'Ödeme Durumu',
    all_invoices_paid: 'Bu projenin tüm faturaları başarıyla ödendi.',
    view_invoices: 'Faturaları Görüntüle',
    rate_experience: 'Deneyiminizi değerlendirin',
    project_completed_success: 'Tebrikler! Projeniz başarıyla tamamlandı. Fikriniz bizim için çok önemli.',
    execution_quality: 'Uygulama Kalitesi',
    describe_experience: 'Deneyiminizi açıklayın',
    write_comment: 'Yorumunuzu buraya yazın...',
    recommend_service: 'Hizmeti tavsiye eder misiniz?',
    later: 'Daha Sonra',
    invoices_tab: 'Faturalar',
    payment_history: 'Ödeme Geçmişi',
    contracts_documents: 'Sözleşmeler ve Belgeler',
    project: 'Proje',
    paid_status: 'Ödendi',
    unpaid_status: 'Ödenmedi',
    pay_invoice: 'Fatura Öde',
    mada_card: 'Mada Kartı',
    successful_transaction: 'Başarılı İşlem',
    ecommerce_contract: 'E-ticaret Proje Sözleşmesi',
    project_contract: 'Proje Sözleşmesi',
    sla_agreement: 'Hizmet Seviyesi Anlaşması (SLA)',
    agreement: 'Anlaşma',
    download_invoice: 'Faturayı İndir',
    commercial_contract: 'Ticari Sözleşme',
    download_contract_btn: 'Sözleşmeyi İndir',
    project_name_placeholder: 'Örnek: E-ticaret Uygulaması',
    project_desc_placeholder: 'Örnek: Uber benzeri, e-cüzdan özellikli bir uygulamaya ihtiyacım var...',
    design_notes_placeholder: 'Örnek: Açık renkleri tercih ederim, modern ve basit bir tasarım istiyorum...',
    company_name: 'AppTech Sistemleri',
    company_address: 'İstanbul, Türkiye',
    vat_label: 'KDV',
    vat_number: '300012345600003',
    cr_label: 'Ticaret Sicil No',
    cr_number: '1010123456',
    invoice_title: 'Vergi Faturası',
    bill_to: 'Fatura Adresi',
    invoice_details: 'Fatura Detayları',
    subtotal: 'Ara Toplam',
    discount: 'İndirim',
    total: 'Toplam',
    vat: 'KDV (%15)',
    grand_total: 'Genel Toplam',
    points_and_discounts: 'Puanlar ve İndirimler',
    used_discount: 'Kullanılan İndirim',
    earned_points: 'Kazanılan Puanlar',
    available_discounts: 'Mevcut İndirimler',
    use_points_discount: '{discount}% indirim almak için {points} puan kullanın',
    not_enough_points: 'Yetersiz puan bakiyesi',
    apply_discount: 'İndirimi Uygula',
    discount_applied: 'İndirim Uygulandı',
    remove_discount: 'Kaldır',
    you_have_points: '{points} puanınız var',
    points_balance: 'Puan Bakiyesi',
    project_status_in_review: 'İnceleme Altında',
    project_status_in_progress: 'Uygulamada',
    project_status_completed: 'Tamamlandı',
    responsible_department: 'Sorumlu Departman',
    request_revision: 'Revizyon İste',
    revision_reason: 'Revizyon Nedeni',
    send_request: 'İsteği Gönder',
    technical_dept_files: 'Teknik Departman Dosyaları',
    source_code_files: 'Kaynak Kod Dosyaları',
    design_files: 'Tasarım Dosyaları',
    database_files: 'Veritabanı Dosyaları',
    other_files: 'Diğer Dosyalar',
    client_files: 'Müşteri Dosyaları',
    no_upload_allowed: 'Burada yeni yüklemelere izin verilmez',
    approve_stage: 'Aşamayı Onayla',
    request_stage_revision: 'Aşama Revizyonu İste',
    stage_suggestions: 'Teknik Departman Gelişmeleri ve Önerileri',
    stage_completed: 'Aşama Tamamlandı',
    stage_pending: 'Bekleyen Aşama',
    stage_in_progress: 'Aşama Devam Ediyor',
    stage_revision: 'Aşama Revizyon Altında',
    last_seen: 'Son Görülme',
    working_hours: 'Çalışma Saatleri',
    seen: 'Görüldü',
    unseen: 'Görülmedi',
    project_description_title: 'Proje Açıklaması',
    progress_percentage: 'İlerleme Yüzdesi',
    technical_chat: 'Teknik Sohbet',
    project_tracking: 'Proje Takibi',
    files_tab: 'Dosyalar',
    overview_tab: 'Genel Bakış',
    revision_submitted: 'Revizyon talebi başarıyla gönderildi',
    stage_approved: 'Aşama başarıyla onaylandı',
    message_placeholder: 'Mesajınızı buraya yazın...',
    send_message: 'Gönder',
    jan: 'Ocak',
    feb: 'Şubat',
    mar: 'Mart',
    apr: 'Nisan',
    may: 'Mayıs',
    jun: 'Haziran',
    jul: 'Temmuz',
    aug: 'Ağustos',
    sep: 'Eylül',
    oct: 'Ekim',
    nov: 'Kasım',
    dec: 'Aralık',
    date_today: 'Salı, 22 Temmuz 2025',
    wd: 'iş günü',
    start_date: 'Başlangıç Tarihi',
    technical_dept: 'Teknik Departman',
    web_mobile_dev: 'Web ve Mobil Uygulama Geliştirme Bölümü',
    days_remaining: 'gün kaldı',
    stage1_title: 'Gereksinim Analizi ve Arayüz Tasarımı',
    stage1_suggestions: 'Temel gereksinim analizi ve ilk kullanıcı arayüzü tasarımları tamamlandı. Müşteri güvenini artırmak için ürün derecelendirme sistemi eklenmesini öneririz.',
    stage2_title: 'Veritabanı ve Arka Uç Geliştirme',
    stage2_suggestions: 'Şu anda veritabanı yapısını oluşturuyoruz. Gelecekte yüksek veri hacmi kararlılığını sağlamak için PostgreSQL kullanılmasını öneririz.',
    stage3_title: 'Arayüz Geliştirme ve API Entegrasyonu',
    stage3_suggestions: 'Bu aşama, önceki aşamanın onaylanmasının hemen ardından başlayacaktır.'
  },
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export const AppProvider: React.FC<{children: React.ReactNode}> = ({ children }) => {
  const [lang, setLang] = useState<Language>('AR');
  const [theme, setTheme] = useState<Theme>('dark');
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  useEffect(() => {
    document.documentElement.dir = lang === 'AR' ? 'rtl' : 'ltr';
    document.title = lang === 'AR' 
      ? 'منصة إنجاز لإدارة المشاريع - ClientFlow' 
      : lang === 'TR' 
        ? 'ClientFlow - Proje Yönetim Platformu' 
        : 'ClientFlow - Project Management Platform';
  }, [lang]);

  const t = (key: string) => {
    return (translations[lang] as any)[key] || key;
  };

  return (
    <AppContext.Provider value={{ lang, setLang, theme, setTheme, t, user, setUser }}>
      {children}
    </AppContext.Provider>
  );
};

export const useAppContext = () => {
  const context = useContext(AppContext);
  if (!context) throw new Error('useAppContext must be used within AppProvider');
  return context;
};
